name: shrine
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  provider: ^6.0.5
  firebase_ui_auth: ^1.3.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  firebase_database: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/popo.png
    - assets/logo.png
    # TODO: Add slanted menu asset (104)
