// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Nn2J082ogniOEiL4JzXFf72kOknT4us',
    appId: '1:690882622298:web:61363dd97da1ee73f07963',
    messagingSenderId: '690882622298',
    projectId: 'final-exam-5a6b6',
    authDomain: 'final-exam-5a6b6.firebaseapp.com',
    storageBucket: 'final-exam-5a6b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-fHy4JJwfErpZ079r6c_JfIzzeSnFU8',
    appId: '1:690882622298:android:b2d02e103f2b68b9f07963',
    messagingSenderId: '690882622298',
    projectId: 'final-exam-5a6b6',
    storageBucket: 'final-exam-5a6b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqd-pv3vuhVGRH20LkvsJz1Kx1kIWfqDU',
    appId: '1:690882622298:ios:ff3177855516b15cf07963',
    messagingSenderId: '690882622298',
    projectId: 'final-exam-5a6b6',
    storageBucket: 'final-exam-5a6b6.appspot.com',
    iosClientId: '690882622298-72qijtm5dftrtnqd2k1vk1dcqcvd7db5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqd-pv3vuhVGRH20LkvsJz1Kx1kIWfqDU',
    appId: '1:690882622298:ios:ff3177855516b15cf07963',
    messagingSenderId: '690882622298',
    projectId: 'final-exam-5a6b6',
    storageBucket: 'final-exam-5a6b6.appspot.com',
    iosClientId: '690882622298-72qijtm5dftrtnqd2k1vk1dcqcvd7db5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalExam',
  );
}
